module.exports = {
  ADD_USER: 'add user',
  FAILED_JOIN: 'failed join',
  USER_JOINED: 'user_joined',
  REMOVE_USER: 'remove user',
  SET_POINT_VALUE: 'set point value',
  SET_VISIBILITY: 'set visibility',
  RESET_POINTS: 'reset points',
  STATE_UPDATE: 'state update',
  NEXT_STORY: 'next story',
  DISCONNECTED: 'disconnected',
  GET_TIMER_STATE: 'get timer state',
  TIMER_UPDATE: 'timer update',
  START_TIMER: 'start timer',
  CONTINUE_TIMER: 'continue timer',
  RESET_TIMER: 'reset timer',
  PAUSE_TIMER: 'pause timer',
  HARD_RESET_TIMER: 'hard reset timer',
  SET_QA_STATUS: 'set qa status',
};
